<a href="https://colab.research.google.com/github/Akash14-09/CP_Coach/blob/main/ML_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Phase 1 --> Data Collection

In [1]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter

In [2]:
handle = "akashdwivedi1409"

url = f"https://codeforces.com/api/user.info?handles={handle}"

response = requests.get(url)

data = response.json()

data

{'status': 'OK',
 'result': [{'lastName': 'Dwivedi',
   'country': 'India',
   'lastOnlineTimeSeconds': 1779934646,
   'city': 'Pratāpgarh',
   'rating': 570,
   'friendOfCount': 31,
   'titlePhoto': 'https://userpic.codeforces.org/4917734/title/d299031c37d157f7.jpg',
   'handle': 'akashdwivedi1409',
   'avatar': 'https://userpic.codeforces.org/4917734/avatar/71bed56776fe2b9e.jpg',
   'firstName': 'Akash',
   'contribution': 0,
   'organization': 'BIET, Jhansi',
   'rank': 'newbie',
   'maxRating': 941,
   'registrationTimeSeconds': 1750341472,
   'maxRank': 'newbie'}]}

In [3]:
user = data['result'][0]

user_info = {
    "handle": user.get("handle"),
    "rating": user.get("rating"),
    "maxRating": user.get("maxRating"),
    "rank": user.get("rank"),
    "maxRank": user.get("maxRank"),
    "contribution": user.get("contribution"),
    "friendOfCount": user.get("friendOfCount")
}

user_info

{'handle': 'akashdwivedi1409',
 'rating': 570,
 'maxRating': 941,
 'rank': 'newbie',
 'maxRank': 'newbie',
 'contribution': 0,
 'friendOfCount': 31}

In [4]:
url = f"https://codeforces.com/api/user.status?handle={handle}"

response = requests.get(url)

data = response.json()

submissions = data['result']

len(submissions)

838

In [5]:
rows = []

for sub in submissions:

    rows.append({
        "submission_id": sub.get("id"),
        "problem_name": sub["problem"].get("name"),
        "rating": sub["problem"].get("rating"),
        "tags": sub["problem"].get("tags"),
        "verdict": sub.get("verdict"),
        "language": sub.get("programmingLanguage"),
        "creation_time": sub.get("creationTimeSeconds")
    })

df = pd.DataFrame(rows)

df.head()

,submission_id,problem_name,rating,tags,verdict,language,creation_time
0,376358373,Consecutive Subsequence,1700.0,[dp],OK,"C++23 (GCC 14-64, msys2)",1779941701
1,376352943,Flowers,1700.0,[dp],OK,"C++23 (GCC 14-64, msys2)",1779936363
2,376325273,Yet Another Broken Keyboard,1200.0,"[combinatorics, dp, implementation]",OK,"C++23 (GCC 14-64, msys2)",1779900360
3,376167553,Number of Ways,1700.0,"[binary search, brute force, data structures, ...",OK,"C++23 (GCC 14-64, msys2)",1779787744
4,376166882,Number of Ways,1700.0,"[binary search, brute force, data structures, ...",WRONG_ANSWER,"C++23 (GCC 14-64, msys2)",1779787303

In [6]:
df['rating'].mean()
#avg of all the problems that i solved till now

np.float64(1082.4050632911392)

In [7]:
df["verdict"].value_counts()

verdict
OK                         462
WRONG_ANSWER               295
TIME_LIMIT_EXCEEDED         38
COMPILATION_ERROR           33
RUNTIME_ERROR                5
MEMORY_LIMIT_EXCEEDED        3
SKIPPED                      1
IDLENESS_LIMIT_EXCEEDED      1
Name: count, dtype: int64

In [8]:
df["language"].value_counts().head(10)

language
C++20 (GCC 13-64)           540
C++23 (GCC 14-64, msys2)    288
GNU C11                       8
C++17 (GCC 7-32)              1
PyPy 3-64                     1
Name: count, dtype: int64

In [9]:
all_tags = []

for tags in df["tags"]:

    if isinstance(tags, list):
        all_tags.extend(tags)

tag_counts = Counter(all_tags)

tag_counts.most_common(10)

[('math', 368),
 ('greedy', 357),
 ('implementation', 261),
 ('brute force', 174),
 ('dp', 160),
 ('sortings', 118),
 ('constructive algorithms', 116),
 ('number theory', 87),
 ('binary search', 76),
 ('data structures', 67)]

In [12]:
#converting the scientific time to readable creation time

In [13]:
df["creation_time"] = pd.to_datetime(
    df["creation_time"],
    unit="s"
)

df.head()

,submission_id,problem_name,rating,tags,verdict,language,creation_time
0,376358373,Consecutive Subsequence,1700.0,[dp],OK,"C++23 (GCC 14-64, msys2)",2026-05-28 04:15:01
1,376352943,Flowers,1700.0,[dp],OK,"C++23 (GCC 14-64, msys2)",2026-05-28 02:46:03
2,376325273,Yet Another Broken Keyboard,1200.0,"[combinatorics, dp, implementation]",OK,"C++23 (GCC 14-64, msys2)",2026-05-27 16:46:00
3,376167553,Number of Ways,1700.0,"[binary search, brute force, data structures, ...",OK,"C++23 (GCC 14-64, msys2)",2026-05-26 09:29:04
4,376166882,Number of Ways,1700.0,"[binary search, brute force, data structures, ...",WRONG_ANSWER,"C++23 (GCC 14-64, msys2)",2026-05-26 09:21:43

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 838 entries, 0 to 837
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   submission_id  838 non-null    int64
 1   problem_name   838 non-null    object
 2   rating         790 non-null    float64
 3   tags           838 non-null    object
 4   verdict        838 non-null    object
 5   language       838 non-null    object
 6   creation_time  838 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 46.0+ KB

In [15]:
df["year"] = df["creation_time"].dt.year
df["month"] = df["creation_time"].dt.month
df["day"] = df["creation_time"].dt.day

In [16]:
df.to_csv("akashdwivedi1409_submissions_updated.csv", index=False)

In [17]:
# from google.colab import files

# files.download("akashdwivedi1409_submissions_updated.csv")

##Phase 2 --> Feature Engineering

###Solve Rate
How many solutions are getting accepted

In [18]:
total_submissions = len(df)

accepted = len(df[df["verdict"] == "OK"])

solve_rate = (accepted / total_submissions) * 100

print("Solve Rate:", round(solve_rate, 2), "%")

Solve Rate: 55.13 %

In [20]:
#avg solved rating
solved_df = df[df["verdict"] == "OK"]
solved_df["rating"].mean()

np.float64(1087.3873873873874)

In [21]:
#Hardest solved problem

In [22]:
solved_df["rating"].max()

2000.0

##Strength Detection :


1.   Accepted Submissions
2.   Problem Difficulty Ratings
3.   Success Rate
4.   Average Solved Difficulty

In [38]:
# Remove rows where rating is missing
strong_df = df[
    (df["verdict"] == "OK") &
    (df["rating"].notnull())
].copy()


topic_strength = {}

for _, row in strong_df.iterrows():

    tags = row["tags"]
    rating = row["rating"]

    if not isinstance(tags, list):
        continue

    for tag in tags:

        if tag not in topic_strength:

            topic_strength[tag] = {

                "solved_count": 0,

                "total_rating": 0,
                "max_rating": 0
            }


        topic_strength[tag]["solved_count"] += 1

        topic_strength[tag]["total_rating"] += rating

        topic_strength[tag]["max_rating"] = max(
            topic_strength[tag]["max_rating"],
            rating
        )


strong_topic_scores = []

for tag, stats in topic_strength.items():

    solved_count = stats["solved_count"]

    avg_rating = (
        stats["total_rating"] / solved_count
    )

    max_rating = stats["max_rating"]



    import math

    mastery_score = (
        math.log1p(solved_count) *
        avg_rating *
        0.7
        +
        max_rating *
        0.3
    )


    strong_topic_scores.append({

        "topic": tag,

        "solved_count": solved_count,

        "average_solved_rating": round(avg_rating, 2),

        "hardest_solved": max_rating,

        "mastery_score": round(mastery_score, 2)
    })


#sort by strong topics --> on the basis of mastery score
strong_topic_scores = sorted(
    strong_topic_scores,
    key=lambda x: x["mastery_score"],
    reverse=True
)

#printing top 10 strong topics
top_n = 10

for topic in strong_topic_scores[:top_n]:

    print(topic)
    print(" ")

{'topic': 'greedy', 'solved_count': 180, 'average_solved_rating': 1079.44, 'hardest_solved': 1700.0, 'mastery_score': 4438.04}

{'topic': 'math', 'solved_count': 184, 'average_solved_rating': 1067.39, 'hardest_solved': 1700.0, 'mastery_score': 4410.51}

{'topic': 'dp', 'solved_count': 100, 'average_solved_rating': 1187.0, 'hardest_solved': 1700.0, 'mastery_score': 4344.7}

{'topic': 'implementation', 'solved_count': 135, 'average_solved_rating': 1061.48, 'hardest_solved': 2000.0, 'mastery_score': 4250.28}

{'topic': 'brute force', 'solved_count': 96, 'average_solved_rating': 1085.42, 'hardest_solved': 2000.0, 'mastery_score': 4075.83}

{'topic': 'binary search', 'solved_count': 48, 'average_solved_rating': 1297.92, 'hardest_solved': 1700.0, 'mastery_score': 4045.88}

{'topic': 'data structures', 'solved_count': 40, 'average_solved_rating': 1290.0, 'hardest_solved': 1700.0, 'mastery_score': 3863.36}

{'topic': 'sortings', 'solved_count': 65, 'average_solved_rating': 1141.54, 'hardest_solved': 1600.0, 'mastery_score': 3827.86}

{'topic': 'two pointers', 'solved_count': 36, 'average_solved_rating': 1305.56, 'hardest_solved': 1700.0, 'mastery_score': 3809.98}

{'topic': 'constructive algorithms', 'solved_count': 59, 'average_solved_rating': 1105.08, 'hardest_solved': 2000.0, 'mastery_score': 3767.22}

weakness detection --> gives you all the failed submissions for each topic

In [40]:
weak_df = df[
    (df["verdict"] != "OK") &
    (df["rating"].notnull())
].copy()

topic_weakness = {}


for _, row in weak_df.iterrows():

    tags = row["tags"]
    rating = row["rating"]

    if not isinstance(tags, list):
        continue

    for tag in tags:


        if tag not in topic_weakness:

            topic_weakness[tag] = {


                "failed_count": 0,


                "failed_rating_sum": 0,

                "hardest_failed": 0
            }


        topic_weakness[tag]["failed_count"] += 1

        topic_weakness[tag]["failed_rating_sum"] += rating

        topic_weakness[tag]["hardest_failed"] = max(
            topic_weakness[tag]["hardest_failed"],
            rating
        )



weak_topic_scores = []

for tag, stats in topic_weakness.items():

    failed_count = stats["failed_count"]

    avg_failed_rating = (
        stats["failed_rating_sum"] / failed_count
    )

    hardest_failed = stats["hardest_failed"]



    import math

    weakness_score = (

        math.log1p(failed_count) *
        avg_failed_rating *
        0.7

        +

        hardest_failed *
        0.3
    )


    weak_topic_scores.append({

        "topic": tag,

        "failed_count": failed_count,

        "average_failed_rating": round(avg_failed_rating, 2),

        "hardest_failed": hardest_failed,

        "weakness_score": round(weakness_score, 2)
    })

weak_topic_scores = sorted(
    weak_topic_scores,
    key=lambda x: x["weakness_score"],
    reverse=True
)

top_n = 10

for topic in weak_topic_scores[:top_n]:

    print(topic)
    print(" ")

{'topic': 'math', 'failed_count': 172, 'average_failed_rating': 1068.02, 'hardest_failed': 1700.0, 'weakness_score': 4362.68}

{'topic': 'greedy', 'failed_count': 155, 'average_failed_rating': 1066.45, 'hardest_failed': 1700.0, 'weakness_score': 4279.8}

{'topic': 'dp', 'failed_count': 57, 'average_failed_rating': 1226.32, 'hardest_failed': 2500.0, 'weakness_score': 4235.57}

{'topic': 'implementation', 'failed_count': 118, 'average_failed_rating': 1039.83, 'hardest_failed': 1700.0, 'weakness_score': 3988.63}

{'topic': 'brute force', 'failed_count': 71, 'average_failed_rating': 1038.03, 'hardest_failed': 2500.0, 'weakness_score': 3857.51}

{'topic': 'number theory', 'failed_count': 40, 'average_failed_rating': 1190.0, 'hardest_failed': 1600.0, 'weakness_score': 3573.41}

{'topic': 'constructive algorithms', 'failed_count': 57, 'average_failed_rating': 1071.93, 'hardest_failed': 1700.0, 'weakness_score': 3556.76}

{'topic': 'sortings', 'failed_count': 48, 'average_failed_rating': 1116.67, 'hardest_failed': 1400.0, 'weakness_score': 3462.11}

{'topic': 'data structures', 'failed_count': 27, 'average_failed_rating': 1248.15, 'hardest_failed': 1700.0, 'weakness_score': 3421.36}

{'topic': 'binary search', 'failed_count': 28, 'average_failed_rating': 1217.86, 'hardest_failed': 1700.0, 'weakness_score': 3380.62}

Rating Distribution Plot

Daily Activity Analysis

Plotting Consistency